### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: IntervalSearchTree$IntervalNode

### ISSUE THREAD

**Issue by tseemann** [ctSkennerton/minced#19]
This is happening randomly - any ideas?

```
Exception in thread "main" java.lang.NoClassDefFoundError: IntervalSearchTree$IntervalNode
        at IntervalSearchTree.add(IntervalSearchTree.java:47)
        at DNASequence.mask(DNASequence.java:363)
        at CRISPRFinder.goCRISPRFinder(CRISPRFinder.java:131)
        at minced.main(minced.java:246)
Caused by: java.lang.ClassNotFoundException: IntervalSearchTree$IntervalNode
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 4 more
```

**Comment by ctSkennerton** [comment]
By randomly you mean on different machines or randomly on the same machine?

**Comment by ctSkennerton** [comment]
Try downloading version 0.3.0 - should have the error fixed and has improved GFF output as a bonus (should also work on older JVM versions too)

**Comment by tseemann** [comment]
Randomly on the same machine. I'm running Prokka on ~20,000 genomes and it happens a lot.

I'll upgrade and start over :)

**Comment by tseemann** [comment]
Made a new brew package - probably need to tell the Conda guys.

**Comment by tseemann** [comment]
@Slugger70 upgrade the whole `minced` package.

**Comment by ctSkennerton** [comment]
@tseemann did this fix your issue? Is it okay to close this now?
